version: "3.8"
services:
  tweets-docker:
    container_name: tweets-container
    image: tweets-docker
    ports:
      - 8080:8080
    build: .
    restart: always
    depends_on:
      - mysqldb
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - D:/DockerDB:/var/lib/mysql
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: tweets
      MYSQL_ROOT_PASSWORD: root